import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import Dummy from '@/components/Dummy'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    <style jsx>
      {`
        .myspan{
          color: red
        }
      `}
    </style>
      <Head>
        <title>Blog Vista</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="nextjx, blog vista, hunting coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className={styles.font}>
        <Dummy></Dummy>

        {/* <Script src='' strategy='lazyOnLoad'></Script> */}
        <nav className={styles.mainNav}>
          <ul>
            <Link href='/'>
              <li>Home</li>
            </Link>
            <Link href='/about'>
              <li>About</li>
            </Link>
            <Link href='/blog'>
              <li>Blog</li>
            </Link>
            <Link href='/contact'>
              <li>Contact</li>
            </Link>

          </ul>
        </nav>

        <main className={`${styles.main}`}>


          <div className={styles.main}>
            <span className='myspan dummy'>

            <h1>Blog Vista</h1>
            </span>
            <p>A blog for hunting coders by blog vista</p>
          </div>


          <div>
            <h2>Popular Blogs</h2>
            <div className="blogItem">
              <h3>How to learn JavaScript in 2023?</h3>
              <p>JavaScript is the language used to design logics for the web</p>
            </div>
            <div className="blogItem">
              <h3>How to learn JavaScript in 2023?</h3>
              <p>JavaScript is the language used to design logics for the web</p>
            </div>
            <div className="blogItem">
              <h3>How to learn JavaScript in 2023?</h3>
              <p>JavaScript is the language used to design logics for the web</p>
            </div>
          </div>
        </main>
      </div>
    </>
  )
  }
